# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424d4409b91c2a49d2622c44ff7e3915c9c3ee8b14a0e2cecce567737ebfe616282e841789b2066aef68d61782f049beafbbb31bfb4562b4243128792a516e00

test:
  secret_key_base: 9b36791331381e75437a9d23d1c820c5e5d592c327f53b6e76fdb103a847d378be9e508f145da8599275024562d6bc346a2cbbae84dd05c6aa0d57ed20f0619a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
